"""second

Revision ID: 05383757cd5e
Revises: e0a76965b162
Create Date: 2023-03-14 13:46:21.344656

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05383757cd5e'
down_revision = 'e0a76965b162'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('token', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_token_token'), 'token', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_token'), table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
