"""third

Revision ID: 40883050b6f4
Revises: 05383757cd5e
Create Date: 2023-03-28 11:16:14.340062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40883050b6f4'
down_revision = '05383757cd5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    # ### end Alembic commands ###
