"""fourth

Revision ID: 931917361d84
Revises: 40883050b6f4
Create Date: 2023-03-31 12:39:20.890156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931917361d84'
down_revision = '40883050b6f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
